#!/bin/sh

#OSNAME="puavo-os"
#CLASS="extra"
#DIST="buster"

CURRENT_IMAGE=$(cat /etc/puavo-image/name)
OSNAME=$(echo $CURRENT_IMAGE|cut -d- -f1-2)
CLASS=$(echo $CURRENT_IMAGE|cut -d- -f3)
DIST=$(echo $CURRENT_IMAGE|cut -d- -f4)

while [ $# -gt 0 ]; do
    case $1 in
	-h|--help)
	    shift
	    echo "Usage: $(basename $0) [options] CHROOT"
	    echo
	    echo "Make a PuavoOS image from a chroot directory."
	    echo
	    echo "Options:"
	    echo "    -o, --osname          set image osname (default: $OSNAME"
	    echo "    -c, --class           set image class (default: $CLASS)"
	    echo "    -d, --dist            set image dist (default: $DIST)"
	    echo
	    exit 0
	    ;;
	-c|--class)
	    shift
	    CLASS=$1
	    shift
	    ;;
	-d|--dist)
	    shift
	    DIST=$1
	    shift
	    ;;
	-o|--osname)
	    shift
	    OSNAME=$1
	    shift
	    ;;
	--)
	    shift
	    break
	    ;;
	-*)
	    usage_error "invalid argument '$1'"
	    ;;
	*)
	    break
	    ;;
    esac
done

if [ $# -ne 1 ]; then
    echo  "invalid number of arguments ($#), expected 1"
    exit 1
fi

CHROOT=$1


if ! test -d $CHROOT;then
    echo "error: chroot $CHROOT not found"
#    exit 1
fi

exit

# clean chroot
test -d $CHROOT/install && rm -r $CHROOT/install
test -d $CHROOT/var/cache/apt/archives/ && rm -r $CHROOT/var/cache/apt/archives/
mkdir $CHROOT/var/cache/apt/archives/


# update some vlaues in /etc/puavo-image
if ! test -f $CHROOT/etc/puavo-image/base_name;then
   cp $CHROOT/etc/puavo-image/name $CHROOT/etc/puavo-image/base_name
fi
if ! test -f $CHROOT/etc/puavo-image/base_release;then
   cp $CHROOT/etc/puavo-image/release $CHROOT/etc/puavo-image/base_release
fi
if ! test -f $CHROOT/etc/puavo-image/base_class;then
   cp $CHROOT/etc/puavo-image/class $CHROOT/etc/puavo-image/base_class
fi
echo "${IMAGE}.img" > $CHROOT/etc/puavo-image/name
echo "$( cat $CHROOT/etc/puavo-image/base_release ) (${VERSION})" > $CHROOT/etc/puavo-image/release
echo "$CLASS" > $CHROOT/etc/puavo-image/class
echo "${IMAGE}.img" > $CHROOT/etc/puavo-image/name
echo "$( cat $CHROOT/etc/puavo-image/release ) (${VERSION})">$CHROOT/etc/puavo-image/release
echo "$CLASS" > $CHROOT/etc/puavo-image/class


#compose new image name
VERSION=$(date +%Y-%m-%d-%H%M%S)
IMAGE="${OSNAME}-${CLASS}-${DIST}-${VERSION}-amd64"


#make compressed image
puavo-dir-clone --dont-update-name --type squashfs $CHROOT ${IMAGE}.img

exit $?

